name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:

  create-env-file:
    runs-on: ubuntu-latest
    steps:
      - name: Create env file
        run: |
          touch .env
          echo API_ENDPOINT=333 >> .env
          echo VITE_APP_KEY=${{ secrets.VITE_APP_KEY }} >> .env
          cat .env

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm install
          npm run-script build -- --base='/SoccerStat/'
#        env: !!!
#          VITE_APP_KEY: ${{ secrets.VITE_APP_KEY }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: master
          folder: dist

      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: /.env